description = "Initializ Distroless base image with buildpacks for Go, NodeJS, Python, Java, .NET Core, PHP, Ruby, Apache HTTPD, NGINX and Procfile"
 
[[buildpacks]]
  uri = "docker://public.ecr.aws/initializ/buildpack/go@sha256:42f3155ea257508b2c414870697b6ed194375c758de213ebe9da3ced729053be"
  version = "1.0.1"
 
[[buildpacks]]
  uri = "docker://public.ecr.aws/initializ/buildpack/nodejs@sha256:437ad4efb145c2308b716ed8a70fc687e27eafbed9509a11129829caada35f02"
  version = "2.2.2"
 
[[buildpacks]]
  uri = "public.ecr.aws/initializ/buildpack/python@sha256:7dd0a9f657bc734ec139f0bb6598277e4c50f2cc3c112e9654a7f6ad4f0f4def"
  version = "4.0.1"
 
[[buildpacks]]
  uri = "docker://public.ecr.aws/initializ/buildpack/java@sha256:3f3d021d44dec366512b57cf84db8ccfbfc39a22cd64353cf16c9b1c7c506b90"
  version = "2.0.1"
 
[[buildpacks]]
  uri = "docker://public.ecr.aws/initializ/buildpack/dotnet-core@sha256:5b3f9c3a82befbcbc6b394d8dd7db4210ec4f897c15d9972614c5ca6f9abd524"
  version = "1.0.8"  
 
[[buildpacks]]
  uri = "docker://public.ecr.aws/initializ/buildpack/php@sha256:5e5d6ea7d6c743de5fd2b9816687bc473821a9fcde37c00b08989885f84a0239"
  version = "1.0.3"   

[[buildpacks]]
  uri = "docker://public.ecr.aws/initializ/buildpack/web-servers@sha256:d3b55c0c619705efd60a10606075c0d1ad1e7945d2203fa46f5cd7e82b807c6c"
  version = "1.0.1" 

[[buildpacks]]
  uri = "docker://public.ecr.aws/initializ/buildpack/java-native-image@sha256:45eb3f0a11cdc10909a3e2892d92b657d9a8d2c9e582401c862c3ecb1c0474f4"
  version = "9.0.0" 

[[buildpacks]]
  uri = "docker://public.ecr.aws/initializ/buildpack/procfile@sha256:fe2979ecc343c1fe8cc13b8d9c0bd931d86503447be2fa5d3d299ecb7a35329e"
  version = "5.6.9" 
 
[[order]]
 
  [[order.group]]
    id = "initializ-buildpacks/go"
    version = "1.0.1"
 
[[order]]
 
  [[order.group]]
    id = "initializ-buildpacks/nodejs"
    version = "2.2.2"
 
[[order]]
 
  [[order.group]]
    id = "initializ-buildpacks/python"
    version = "4.0.1"
 
 
[[order]]
 
  [[order.group]]
    id = "initializ-buildpacks/java"
    version = "2.0.1"
 
[[order]]
 
  [[order.group]]
    id = "initializ-buildpacks/dotnet-core"
    version = "1.0.8"
 
[[order]]
 
  [[order.group]]
    id = "initializ-buildpacks/php"
    version = "1.0.3"    

[[order]]
 
  [[order.group]]
    id = "initializ-buildpacks/web-servers"
    version = "1.0.1" 

[[order]]
 
  [[order.group]]
    id = "initializ-buildpacks/java-native-image"
    version = "9.0.0"

[[order]]
 
  [[order.group]]
    id = "initializ-buildpacks/procfile"
    version = "5.6.9"
 

# Base images used to create the builder
[stack]
  build-image = "public.ecr.aws/initializ/builder/build-image-labeled:latest"
  id = "Initializ Distroless Stack"
  run-image = "public.ecr.aws/initializ/builder/run-image-labeled:latest"
  run-image-mirrors = []